const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b",
    },
    price: 1500,
    location: "Malibu",
    country: "United States",
    category: "beachfront",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    },
    price: 1200,
    location: "New York City",
    country: "United States",
    category: "iconic-cities",
  },
  {
    title: "Mountain Retreat",
    description: "Peaceful mountain cabin.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d",
    },
    price: 1000,
    location: "Aspen",
    country: "United States",
    category: "mountains",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience Tuscany charm.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
    },
    price: 2500,
    location: "Florence",
    country: "Italy",
    category: "iconic-cities",
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among treetops.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
    },
    price: 800,
    location: "Portland",
    country: "United States",
    category: "camping",
  },
  {
    title: "Beachfront Paradise",
    description: "Ultimate beach relaxation.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9",
    },
    price: 2000,
    location: "Cancun",
    country: "Mexico",
    category: "beachfront",
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Lake side cabin.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b",
    },
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
    category: "mountains",
  },
  {
    title: "Luxury Penthouse",
    description: "City luxury living.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd",
    },
    price: 3500,
    location: "Los Angeles",
    country: "United States",
    category: "trending",
  },
  {
    title: "Ski Chalet",
    description: "Swiss Alps chalet.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb",
    },
    price: 3000,
    location: "Switzerland",
    country: "Switzerland",
    category: "mountains",
  },
  {
    title: "Safari Lodge",
    description: "Wild safari experience.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e",
    },
    price: 4000,
    location: "Tanzania",
    country: "Tanzania",
    category: "trending",
  },
  {
    title: "Historic Canal House",
    description: "Amsterdam stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4",
    },
    price: 1800,
    location: "Amsterdam",
    country: "Netherlands",
    category: "iconic-cities",
  },
  {
    title: "Private Island",
    description: "Exclusive island stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972",
    },
    price: 10000,
    location: "Fiji",
    country: "Fiji",
    category: "trending",
  },
  {
    title: "Cotswolds Cottage",
    description: "UK countryside.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f",
    },
    price: 1200,
    location: "UK",
    country: "United Kingdom",
    category: "farms",
  },
  {
    title: "Beach Bungalow Bali",
    description: "Relax in Bali.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602391833977-358a52198938",
    },
    price: 1800,
    location: "Bali",
    country: "Indonesia",
    category: "beachfront",
  },
  {
    title: "Castle in Scotland",
    description: "Live like royalty.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98",
    },
    price: 4000,
    location: "Scotland",
    country: "UK",
    category: "castles",
  },
  {
    title: "Desert Oasis Dubai",
    description: "Luxury desert stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1518684079-3c830dcef090",
    },
    price: 5000,
    location: "Dubai",
    country: "UAE",
    category: "trending",
  },
  {
    title: "Villa in Greece",
    description: "Mediterranean stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f",
    },
    price: 2500,
    location: "Greece",
    country: "Greece",
    category: "beachfront",
  },
  {
    title: "Treehouse Costa Rica",
    description: "Eco-friendly stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7",
    },
    price: 750,
    location: "Costa Rica",
    country: "Costa Rica",
    category: "camping",
  },
  {
    title: "Apartment Tokyo",
    description: "Modern city stay.",
    image: {
      filename: "listingimage",
      url: "https://images.unsplash.com/photo-1480796927426-f609979314bd",
    },
    price: 2000,
    location: "Tokyo",
    country: "Japan",
    category: "iconic-cities",
  },
];

module.exports = { data: sampleListings };